In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(rc={'figure.figsize':(15,10)})

In [2]:
df = pd.read_csv('/content/weatherAUS.csv')
df.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  01-12-08   Albury     13.4     22.9       0.6          NaN       NaN   
1  02-12-08   Albury      7.4     25.1       0.0          NaN       NaN   
2  03-12-08   albury     12.9     25.7       0.0          NaN       NaN   
3  04-12-08   albury      9.2     28.0       0.0          NaN       NaN   
4  05-12-08   albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         no   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         no   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         no   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         no   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         no   

   RainTomorrow  
0             N  
1             N  
2             Y  
3            No  
4            No  

[5 rows x 23 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54845 entries, 0 to 54844
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Date           54845 non-null  object 
 1   Location       54825 non-null  object 
 2   MinTemp        54230 non-null  float64
 3   MaxTemp        54402 non-null  float64
 4   Rainfall       53416 non-null  float64
 5   Evaporation    24047 non-null  float64
 6   Sunshine       18441 non-null  float64
 7   WindGustDir    48998 non-null  object 
 8   WindGustSpeed  49004 non-null  float64
 9   WindDir9am     48601 non-null  object 
 10  WindDir3pm     52166 non-null  object 
 11  WindSpeed9am   53492 non-null  float64
 12  WindSpeed3pm   52871 non-null  float64
 13  Humidity9am    53618 non-null  float64
 14  Humidity3pm    53138 non-null  float64
 15  Pressure9am    45067 non-null  float64
 16  Pressure3pm    45117 non-null  float64
 17  Cloud9am       29614 non-null  float64
 18  Cloud3

- We have missing values

In [4]:
df.describe()

MinTemp       MaxTemp      Rainfall   Evaporation      Sunshine  \
count  54230.000000  54402.000000  53416.000000  24047.000000  18441.000000   
mean      11.993087     22.772808      2.679162      5.528760      7.568706   
std        6.429549      6.762894      9.252480      4.483735      3.798647   
min       -8.500000     -4.800000      0.000000      0.000000      0.000000   
25%        7.500000     18.500000      0.000000      2.800000      4.900000   
50%       12.600000     22.500000      0.000000      4.600000      8.600000   
75%       17.100000     26.900000      0.600000      7.200000     10.500000   
max       29.700000     47.300000    371.000000    145.000000     14.100000   

       WindGustSpeed  WindSpeed9am  WindSpeed3pm   Humidity9am   Humidity3pm  \
count   49004.000000  53492.000000  52871.000000  53618.000000  53138.000000   
mean       39.216901     12.858652     17.740519     70.553042     52.827355   
std        14.124110      9.065700      9.258292     17.584445     20.748423   
min         7.000000      0.000000      0.000000      3.000000      1.000000   
25%        30.000000      6.000000     11.000000     59.000000     37.000000   
50%        37.000000     11.000000     17.000000     71.000000     52.000000   
75%        48.000000     19.000000     24.000000     84.000000     67.000000   
max       135.000000    130.000000     83.000000    100.000000    100.000000   

        Pressure9am   Pressure3pm      Cloud9am      Cloud3pm       Temp9am  \
count  45067.000000  45117.000000  29614.000000  29176.000000  53916.000000   
mean    1018.348754   1015.783328      4.432160      4.487216     16.609954   
std        6.851227      6.754559      2.931501      2.723280      6.069559   
min      980.500000    979.000000      0.000000      0.000000     -7.200000   
25%     1013.800000   1011.200000      1.000000      2.000000     12.600000   
50%     1018.400000   1015.800000      5.000000      5.000000     17.200000   
75%     1023.000000   1020.300000      7.000000      7.000000     21.100000   
max     1040.600000   1037.900000      9.000000      8.000000     37.700000   

            Temp3pm  
count  53393.000000  
mean      21.344577  
std        6.579746  
min       -5.400000  
25%       17.200000  
50%       21.000000  
75%       25.300000  
max       46.700000

## Dealing with missing values

In [5]:
df.isna().sum() / len(df)*100

Date              0.000000
Location          0.036466
MinTemp           1.121342
MaxTemp           0.807731
Rainfall          2.605525
Evaporation      56.154618
Sunshine         66.376151
WindGustDir      10.660954
WindGustSpeed    10.650014
WindDir9am       11.384812
WindDir3pm        4.884675
WindSpeed9am      2.466952
WindSpeed3pm      3.599234
Humidity9am       2.237214
Humidity3pm       3.112408
Pressure9am      17.828426
Pressure3pm      17.737260
Cloud9am         46.004194
Cloud3pm         46.802808
Temp9am           1.693865
Temp3pm           2.647461
RainToday         2.607348
RainTomorrow      2.605525
dtype: float64

In [6]:
df.isna().sum() / len(df)*100

Date              0.000000
Location          0.036466
MinTemp           1.121342
MaxTemp           0.807731
Rainfall          2.605525
Evaporation      56.154618
Sunshine         66.376151
WindGustDir      10.660954
WindGustSpeed    10.650014
WindDir9am       11.384812
WindDir3pm        4.884675
WindSpeed9am      2.466952
WindSpeed3pm      3.599234
Humidity9am       2.237214
Humidity3pm       3.112408
Pressure9am      17.828426
Pressure3pm      17.737260
Cloud9am         46.004194
Cloud3pm         46.802808
Temp9am           1.693865
Temp3pm           2.647461
RainToday         2.607348
RainTomorrow      2.605525
dtype: float64

In [7]:
# let's drop na values in location
df.dropna(axis=0, subset=['Location'], inplace=True)

### Categories data

In [8]:
from sklearn.impute import SimpleImputer
cat_imputer = SimpleImputer(strategy='most_frequent')
df[df.columns[df.dtypes=='object']] = cat_imputer.fit_transform(df[df.columns[df.dtypes=='object']])

### Numerical data

In [9]:
from sklearn.impute import KNNImputer
num_imputer = KNNImputer(n_neighbors=3)
df[df.columns[df.dtypes!='object']] = num_imputer.fit_transform(df[df.columns[df.dtypes!='object']])

In [11]:
df.isna().sum() / len(df)*100

Date             0.0
Location         0.0
MinTemp          0.0
MaxTemp          0.0
Rainfall         0.0
Evaporation      0.0
Sunshine         0.0
WindGustDir      0.0
WindGustSpeed    0.0
WindDir9am       0.0
WindDir3pm       0.0
WindSpeed9am     0.0
WindSpeed3pm     0.0
Humidity9am      0.0
Humidity3pm      0.0
Pressure9am      0.0
Pressure3pm      0.0
Cloud9am         0.0
Cloud3pm         0.0
Temp9am          0.0
Temp3pm          0.0
RainToday        0.0
RainTomorrow     0.0
dtype: float64

no missing values

## Convert Categories data

In [12]:
# from date convert to day, month
df['Date'] = pd.to_datetime(df['Date'])
df['day'] = df['Date'].dt.day
df['month'] = df['Date'].dt.month

In [13]:
# drop date
df.drop('Date', axis=1, inplace=True)

### label encoding

In [14]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()
encoder.fit(df[['Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm']])
df[['Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm']] = encoder.transform(df[['Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm']])

In [15]:
df['RainToday'] = df['RainToday'].apply(lambda s : 1 if s=='yes' or s=='Yes' else 0)

In [16]:
df['RainToday'].value_counts()

0    42827
1    11998
Name: RainToday, dtype: int64

In [17]:
df['RainTomorrow'] = df['RainTomorrow'].apply(lambda s : 1 if s=='Yes' or s=='Y' else 0)

In [18]:
df['RainTomorrow'].value_counts()

0    42825
1    12000
Name: RainTomorrow, dtype: int64

In [19]:
df.columns

Index(['Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow', 'day', 'month'],
      dtype='object')

## Detect outliers

In [21]:
!pip install datasist
from datasist.structdata import detect_outliers

In [22]:
for i in ['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine','WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm','WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm','Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am','Temp3pm']:
    Q1 = df[i].quantile(0.25)
    Q3 = df[i].quantile(0.75)
    IQR = Q3 - Q1

    upper = Q3 + IQR * 1.5
    down = Q1 - IQR * 1.5

    values = df[i].apply(lambda val:val if val < upper and val > down else 0)
    
    indecs = detect_outliers(df, n=0, features=[i])
    df.loc[indecs, i] = values.mean()

In [23]:
x = df.drop('RainTomorrow', axis=1)
y = df['RainTomorrow']

In [24]:
y.value_counts()

0    42825
1    12000
Name: RainTomorrow, dtype: int64

## Over sample the data

In [29]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler()
X_resampled, y_resampled = ros.fit_resample(x, y)

## Scale the data

In [30]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_resampled)
X_resampled = scaler.transform(X_resampled)

## Split data

In [45]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X_resampled,y_resampled,test_size=0.2,stratify=y_resampled,random_state=42)

## Apply model
#### from analysis the data we notice 
- not all features linearly correlated so, exclude logistic regression
- there is some Overlapping in data so, exclude K neighbor classifier
- algo with tree based is  a good choice for this data

In [46]:
# algorithms

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
# prediction details
from sklearn.metrics import confusion_matrix, accuracy_score

In [47]:
models = {
    "DT": DecisionTreeClassifier(),
    "RF": RandomForestClassifier(),
    "XGB": XGBClassifier(eval_metric='mlogloss')
}

In [48]:
for name, model in models.items():
    print(f'Training Model {name} \n--------------')
    model.fit(xtrain, ytrain)
    ypred = model.predict(xtest)
    print(f'Training Accuracy: {model.score(xtrain, ytrain)}')
    print(f'Testing Accuracy: {accuracy_score(ytest, ypred)}')
    print(f'Testing Confusion Matrix: \n{confusion_matrix(ytest, ypred)}')
    print('-'*30)

Training Model DT 
--------------
Training Accuracy: 0.9999708114419148
Testing Accuracy: 0.9046117921774665
Testing Confusion Matrix: 
[[7124 1441]
 [ 193 8372]]
------------------------------
Training Model RF 
--------------
Training Accuracy: 0.9999708114419148
Testing Accuracy: 0.9500291885580853
Testing Confusion Matrix: 
[[7872  693]
 [ 163 8402]]
------------------------------
Training Model XGB 
--------------
Training Accuracy: 0.7792469352014011
Testing Accuracy: 0.778225335668418
Testing Confusion Matrix: 
[[6708 1857]
 [1942 6623]]
------------------------------


### use Random forest algorithm

In [49]:
model = RandomForestClassifier()
model.fit(xtrain, ytrain)
ypred = model.predict(xtest)
model.score(xtrain, ytrain)

0.9999708114419148

In [51]:
accuracy_score(ytest, ypred)

0.9506713368359603

In [52]:
confusion_matrix(ytest, ypred)

array([[7874,  691],
       [ 154, 8411]])